"""remove duplicate active indexes

Revision ID: 492481471944
Revises: 6649c79c9e5e
Create Date: 2026-06-10 05:47:16.503438
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '492481471944'
down_revision: Union[str, None] = '6649c79c9e5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_analysis_configs_is_active', table_name='analysis_configs')
    op.drop_index('ix_analysis_signals_is_active', table_name='analysis_signals')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_analysis_signals_is_active', 'analysis_signals', ['is_active'], unique=False)
    op.create_index('ix_analysis_configs_is_active', 'analysis_configs', ['is_active'], unique=False)
    # ### end Alembic commands ###
