"""create phase 1 tables

Revision ID: 6649c79c9e5e
Revises: 
Create Date: 2026-06-10 05:46:27.555614
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6649c79c9e5e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('ETF', 'Stock', 'Index', name='stock_type'), nullable=False),
    sa.Column('market', sa.Enum('US', name='stock_market'), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_stocks_is_active'), 'stocks', ['is_active'], unique=False)
    op.create_index(op.f('ix_stocks_symbol'), 'stocks', ['symbol'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('role', sa.Enum('admin', 'user', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'banned', name='user_status'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('alert_rules',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('stock_id', sa.BigInteger(), nullable=False),
    sa.Column('alert_type', sa.Enum('any_signal', 'buy_signal', 'sell_signal', name='alert_type'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'stock_id', 'alert_type', name='uq_user_stock_type'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_alert_rule_active', 'alert_rules', ['is_active'], unique=False)
    op.create_index(op.f('ix_alert_rules_stock_id'), 'alert_rules', ['stock_id'], unique=False)
    op.create_index(op.f('ix_alert_rules_user_id'), 'alert_rules', ['user_id'], unique=False)
    op.create_table('analysis_configs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('strategy_type', sa.Enum('ma_cross', 'multi_indicator', 'custom_script', name='strategy_type'), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('script_content', sa.Text(), nullable=True),
    sa.Column('script_params', sa.JSON(), nullable=True),
    sa.Column('confirm_bars', sa.Integer(), nullable=False),
    sa.Column('volume_confirm', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_active_stock', 'analysis_configs', ['is_active', 'stock_id'], unique=False)
    op.create_index(op.f('ix_analysis_configs_is_active'), 'analysis_configs', ['is_active'], unique=False)
    op.create_index(op.f('ix_analysis_configs_stock_id'), 'analysis_configs', ['stock_id'], unique=False)
    op.create_table('stock_prices_daily',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.BigInteger(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.DECIMAL(precision=12, scale=4), nullable=False),
    sa.Column('high', sa.DECIMAL(precision=12, scale=4), nullable=False),
    sa.Column('low', sa.DECIMAL(precision=12, scale=4), nullable=False),
    sa.Column('close', sa.DECIMAL(precision=12, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('data_source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'trade_date', name='uq_stock_date'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_stock_date', 'stock_prices_daily', ['stock_id', 'trade_date'], unique=False)
    op.create_index(op.f('ix_stock_prices_daily_trade_date'), 'stock_prices_daily', ['trade_date'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('refresh_token', sa.String(length=500), nullable=False),
    sa.Column('device_info', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_user_sessions_expires_at'), 'user_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('analysis_signals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.BigInteger(), nullable=False),
    sa.Column('config_id', sa.BigInteger(), nullable=False),
    sa.Column('signal_type', sa.Enum('buy', 'sell', name='signal_type'), nullable=False),
    sa.Column('signal_subtype', sa.String(length=50), nullable=True),
    sa.Column('strength', sa.Enum('weak', 'normal', 'strong', name='signal_strength'), nullable=False),
    sa.Column('confidence', sa.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('trigger_price', sa.DECIMAL(precision=12, scale=4), nullable=False),
    sa.Column('trigger_details', sa.JSON(), nullable=False),
    sa.Column('triggered_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['analysis_configs.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_active_signals', 'analysis_signals', ['is_active'], unique=False)
    op.create_index('idx_stock_triggered', 'analysis_signals', ['stock_id', 'triggered_date'], unique=False)
    op.create_index(op.f('ix_analysis_signals_config_id'), 'analysis_signals', ['config_id'], unique=False)
    op.create_index(op.f('ix_analysis_signals_is_active'), 'analysis_signals', ['is_active'], unique=False)
    op.create_index(op.f('ix_analysis_signals_triggered_date'), 'analysis_signals', ['triggered_date'], unique=False)
    op.create_table('backtest_results',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('stock_id', sa.BigInteger(), nullable=False),
    sa.Column('config_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('running', 'completed', 'failed', name='backtest_status'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('initial_capital', sa.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('slippage_pct', sa.DECIMAL(precision=6, scale=4), nullable=False),
    sa.Column('commission_pct', sa.DECIMAL(precision=6, scale=4), nullable=False),
    sa.Column('total_return', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('cagr', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('max_drawdown', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('sharpe_ratio', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('sortino_ratio', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('calmar_ratio', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('win_rate', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('profit_factor', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('num_trades', sa.Integer(), nullable=True),
    sa.Column('benchmark_return', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('equity_curve', sa.JSON(), nullable=True),
    sa.Column('drawdown_curve', sa.JSON(), nullable=True),
    sa.Column('monthly_returns', sa.JSON(), nullable=True),
    sa.Column('trade_log', sa.JSON(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['analysis_configs.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_backtest_results_config_id'), 'backtest_results', ['config_id'], unique=False)
    op.create_index(op.f('ix_backtest_results_stock_id'), 'backtest_results', ['stock_id'], unique=False)
    op.create_index(op.f('ix_backtest_results_user_id'), 'backtest_results', ['user_id'], unique=False)
    op.create_table('ai_analysis_results',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.BigInteger(), nullable=False),
    sa.Column('model_provider', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.DECIMAL(precision=10, scale=6), nullable=False),
    sa.Column('analysis_json', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['analysis_signals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('alert_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('alert_rule_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('stock_id', sa.BigInteger(), nullable=False),
    sa.Column('signal_id', sa.BigInteger(), nullable=True),
    sa.Column('channel', sa.Enum('email', name='alert_channel'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('sent', 'failed', name='alert_status'), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_rule_id'], ['alert_rules.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['analysis_signals.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_user_sent', 'alert_logs', ['user_id', 'sent_at'], unique=False)
    op.create_index(op.f('ix_alert_logs_stock_id'), 'alert_logs', ['stock_id'], unique=False)
    op.create_index(op.f('ix_alert_logs_user_id'), 'alert_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_logs_user_id'), table_name='alert_logs')
    op.drop_index(op.f('ix_alert_logs_stock_id'), table_name='alert_logs')
    op.drop_index('idx_user_sent', table_name='alert_logs')
    op.drop_table('alert_logs')
    op.drop_table('ai_analysis_results')
    op.drop_index(op.f('ix_backtest_results_user_id'), table_name='backtest_results')
    op.drop_index(op.f('ix_backtest_results_stock_id'), table_name='backtest_results')
    op.drop_index(op.f('ix_backtest_results_config_id'), table_name='backtest_results')
    op.drop_table('backtest_results')
    op.drop_index(op.f('ix_analysis_signals_triggered_date'), table_name='analysis_signals')
    op.drop_index(op.f('ix_analysis_signals_is_active'), table_name='analysis_signals')
    op.drop_index(op.f('ix_analysis_signals_config_id'), table_name='analysis_signals')
    op.drop_index('idx_stock_triggered', table_name='analysis_signals')
    op.drop_index('idx_active_signals', table_name='analysis_signals')
    op.drop_table('analysis_signals')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_expires_at'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_stock_prices_daily_trade_date'), table_name='stock_prices_daily')
    op.drop_index('idx_stock_date', table_name='stock_prices_daily')
    op.drop_table('stock_prices_daily')
    op.drop_index(op.f('ix_analysis_configs_stock_id'), table_name='analysis_configs')
    op.drop_index(op.f('ix_analysis_configs_is_active'), table_name='analysis_configs')
    op.drop_index('idx_active_stock', table_name='analysis_configs')
    op.drop_table('analysis_configs')
    op.drop_index(op.f('ix_alert_rules_user_id'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_stock_id'), table_name='alert_rules')
    op.drop_index('idx_alert_rule_active', table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_stocks_symbol'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_is_active'), table_name='stocks')
    op.drop_table('stocks')
    # ### end Alembic commands ###
