"""widen backtest metric columns

Revision ID: bfabf0a0f40b
Revises: 492481471944
Create Date: 2026-06-22 10:12:10.923500
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = 'bfabf0a0f40b'
down_revision: Union[str, None] = '492481471944'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('backtest_results', 'total_return',
               existing_type=mysql.DECIMAL(precision=8, scale=4),
               type_=sa.DECIMAL(precision=18, scale=6),
               existing_nullable=True)
    op.alter_column('backtest_results', 'cagr',
               existing_type=mysql.DECIMAL(precision=8, scale=4),
               type_=sa.DECIMAL(precision=18, scale=6),
               existing_nullable=True)
    op.alter_column('backtest_results', 'max_drawdown',
               existing_type=mysql.DECIMAL(precision=8, scale=4),
               type_=sa.DECIMAL(precision=18, scale=6),
               existing_nullable=True)
    op.alter_column('backtest_results', 'sharpe_ratio',
               existing_type=mysql.DECIMAL(precision=8, scale=4),
               type_=sa.DECIMAL(precision=18, scale=6),
               existing_nullable=True)
    op.alter_column('backtest_results', 'sortino_ratio',
               existing_type=mysql.DECIMAL(precision=8, scale=4),
               type_=sa.DECIMAL(precision=18, scale=6),
               existing_nullable=True)
    op.alter_column('backtest_results', 'calmar_ratio',
               existing_type=mysql.DECIMAL(precision=8, scale=4),
               type_=sa.DECIMAL(precision=18, scale=6),
               existing_nullable=True)
    op.alter_column('backtest_results', 'win_rate',
               existing_type=mysql.DECIMAL(precision=8, scale=4),
               type_=sa.DECIMAL(precision=18, scale=6),
               existing_nullable=True)
    op.alter_column('backtest_results', 'profit_factor',
               existing_type=mysql.DECIMAL(precision=8, scale=4),
               type_=sa.DECIMAL(precision=18, scale=6),
               existing_nullable=True)
    op.alter_column('backtest_results', 'benchmark_return',
               existing_type=mysql.DECIMAL(precision=8, scale=4),
               type_=sa.DECIMAL(precision=18, scale=6),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('backtest_results', 'benchmark_return',
               existing_type=sa.DECIMAL(precision=18, scale=6),
               type_=mysql.DECIMAL(precision=8, scale=4),
               existing_nullable=True)
    op.alter_column('backtest_results', 'profit_factor',
               existing_type=sa.DECIMAL(precision=18, scale=6),
               type_=mysql.DECIMAL(precision=8, scale=4),
               existing_nullable=True)
    op.alter_column('backtest_results', 'win_rate',
               existing_type=sa.DECIMAL(precision=18, scale=6),
               type_=mysql.DECIMAL(precision=8, scale=4),
               existing_nullable=True)
    op.alter_column('backtest_results', 'calmar_ratio',
               existing_type=sa.DECIMAL(precision=18, scale=6),
               type_=mysql.DECIMAL(precision=8, scale=4),
               existing_nullable=True)
    op.alter_column('backtest_results', 'sortino_ratio',
               existing_type=sa.DECIMAL(precision=18, scale=6),
               type_=mysql.DECIMAL(precision=8, scale=4),
               existing_nullable=True)
    op.alter_column('backtest_results', 'sharpe_ratio',
               existing_type=sa.DECIMAL(precision=18, scale=6),
               type_=mysql.DECIMAL(precision=8, scale=4),
               existing_nullable=True)
    op.alter_column('backtest_results', 'max_drawdown',
               existing_type=sa.DECIMAL(precision=18, scale=6),
               type_=mysql.DECIMAL(precision=8, scale=4),
               existing_nullable=True)
    op.alter_column('backtest_results', 'cagr',
               existing_type=sa.DECIMAL(precision=18, scale=6),
               type_=mysql.DECIMAL(precision=8, scale=4),
               existing_nullable=True)
    op.alter_column('backtest_results', 'total_return',
               existing_type=sa.DECIMAL(precision=18, scale=6),
               type_=mysql.DECIMAL(precision=8, scale=4),
               existing_nullable=True)
    # ### end Alembic commands ###
